name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: sfml
      run: sudo apt install libsfml-dev
    - name: make
      run: make
    - name: install mingw
      run: sudo apt install g++-mingw-w64
    - name: install sfml for mingw
      run: wget https://www.sfml-dev.org/files/SFML-2.5.1-windows-gcc-7.3.0-mingw-64-bit.zip; ls /usr 
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu
        path: |
          bin/
          assets
        if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`

