name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: sfml
      run: sudo apt install libsfml-dev
    - name: make
      run: make
    - name: install mingw
      run: sudo apt install g++-mingw-w64
    - name: build windows
      run: make windows
    - uses: "./packages/automatic-releases/"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            bin/*
            assets/
        id: "automatic_releases"
    
