name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: sfml
      run: sudo apt install libsfml-dev
    - name: make
      run: make
    - name: install mingw
      run: sudo apt install g++-mingw-w64
    - name: GitHub Releases
      uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_COMPRESS: xz
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
